// <auto-generated />
using System;
using EggIncognito.Data.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EggIncognito.Data.Migrations
{
    [DbContext(typeof(EggIncognitoDbContext))]
    [Migration("20260612084547_AddHostedCapture")]
    partial class AddHostedCapture
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EggIncognito.Data.Models.CaptureProxyToken", b =>
                {
                    b.Property<string>("DiscordId")
                        .HasColumnType("text")
                        .HasColumnName("discord_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.HasKey("DiscordId");

                    b.ToTable("capture_proxy_tokens");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.CaptureUserCa", b =>
                {
                    b.Property<string>("DiscordId")
                        .HasColumnType("text")
                        .HasColumnName("discord_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<byte[]>("Pfx")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("pfx");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thumbprint");

                    b.HasKey("DiscordId");

                    b.ToTable("capture_user_cas");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.Doc", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BodyMd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_md");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("OwnerUserId")
                        .HasColumnType("text")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("SubjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_key");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_kind");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("SubjectKind", "SubjectKey")
                        .IsUnique();

                    b.ToTable("docs");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.DocImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ByteSize")
                        .HasColumnType("integer")
                        .HasColumnName("byte_size");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("bytes");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("OwnerUserId")
                        .HasColumnType("text")
                        .HasColumnName("owner_user_id");

                    b.HasKey("Id");

                    b.ToTable("doc_images");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.StoredEndpoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Eid")
                        .HasColumnType("text")
                        .HasColumnName("eid");

                    b.Property<string>("OwnerUserId")
                        .HasColumnType("text")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_json");

                    b.Property<string>("ResponseType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Path", "Eid")
                        .IsUnique();

                    b.ToTable("stored_endpoints");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.StoredRoute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("OwnerUserId")
                        .HasColumnType("text")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<bool>("PathParam")
                        .HasColumnType("boolean")
                        .HasColumnName("path_param");

                    b.Property<bool>("PathParamOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("path_param_only");

                    b.Property<string>("RawResponse")
                        .HasColumnType("text")
                        .HasColumnName("raw_response");

                    b.Property<string>("RequestType")
                        .HasColumnType("text")
                        .HasColumnName("request_type");

                    b.Property<bool>("RequestWrapped")
                        .HasColumnType("boolean")
                        .HasColumnName("request_wrapped");

                    b.Property<string>("ResponseType")
                        .HasColumnType("text")
                        .HasColumnName("response_type");

                    b.Property<bool>("ResponseWrapped")
                        .HasColumnType("boolean")
                        .HasColumnName("response_wrapped");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("Source");

                    b.ToTable("stored_routes");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.SubjectTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("SubjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_key");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_kind");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint")
                        .HasColumnName("tag_id");

                    b.HasKey("Id");

                    b.HasIndex("SubjectKind", "SubjectKey", "TagId")
                        .IsUnique();

                    b.ToTable("subject_tags");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tags");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.User", b =>
                {
                    b.Property<string>("DiscordId")
                        .HasColumnType("text")
                        .HasColumnName("discord_id");

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("viewer")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("DiscordId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
