// <auto-generated />
using System;
using EggIncognito.Data.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EggIncognito.Data.Migrations
{
    [DbContext(typeof(EggIncognitoDbContext))]
    [Migration("20260712020000_RetypeOwnerAuthorUserIdColumns")]
    partial class RetypeOwnerAuthorUserIdColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EggIncognito.Data.Models.BackfillJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("Imported")
                        .HasColumnType("integer")
                        .HasColumnName("imported");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("StartedBy")
                        .HasColumnType("text")
                        .HasColumnName("started_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int?>("Total")
                        .HasColumnType("integer")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("Source", "StartedAt");

                    b.ToTable("backfill_jobs");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.CaptureProxyAddr", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Addr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("addr");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DiscordId")
                        .HasColumnType("text")
                        .HasColumnName("discord_id");

                    b.HasKey("UserId");

                    b.HasIndex("Addr")
                        .IsUnique();

                    b.ToTable("capture_proxy_addrs");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.CaptureUserCa", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DiscordId")
                        .HasColumnType("text")
                        .HasColumnName("discord_id");

                    b.Property<byte[]>("Pfx")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("pfx");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thumbprint");

                    b.HasKey("UserId");

                    b.ToTable("capture_user_cas");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.Device", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("Package")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("package");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target");

                    b.HasKey("Id");

                    b.ToTable("devices");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.DeviceProbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<string>("InstalledAppVersion")
                        .HasColumnType("text")
                        .HasColumnName("installed_app_version");

                    b.Property<string>("InstalledBuild")
                        .HasColumnType("text")
                        .HasColumnName("installed_build");

                    b.Property<string>("LatestAvailable")
                        .HasColumnType("text")
                        .HasColumnName("latest_available");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("ProbedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("probed_at");

                    b.Property<bool>("Reachable")
                        .HasColumnType("boolean")
                        .HasColumnName("reachable");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("triggered_by");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "ProbedAt");

                    b.ToTable("device_probes");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.DeviceUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<string>("FromVersion")
                        .HasColumnType("text")
                        .HasColumnName("from_version");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("ToVersion")
                        .HasColumnType("text")
                        .HasColumnName("to_version");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("triggered_by");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "AttemptedAt");

                    b.ToTable("device_updates");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.Doc", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BodyMd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_md");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("SubjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_key");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_kind");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("SubjectKind", "SubjectKey")
                        .IsUnique();

                    b.ToTable("docs");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.DocImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ByteSize")
                        .HasColumnType("integer")
                        .HasColumnName("byte_size");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("bytes");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.HasKey("Id");

                    b.ToTable("doc_images");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.EnvDesign", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("env_designs");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.EnvDesignVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("DesignId")
                        .HasColumnType("bigint")
                        .HasColumnName("design_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int?>("RolledBackFrom")
                        .HasColumnType("integer")
                        .HasColumnName("rolled_back_from");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.HasKey("Id");

                    b.HasIndex("DesignId", "VersionNo")
                        .IsUnique();

                    b.ToTable("env_design_versions");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.ExtractJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_version");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Platform", "AppVersion")
                        .IsUnique();

                    b.ToTable("extract_jobs");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.FeedDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<int>("ProtoVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("proto_version_id");

                    b.Property<int?>("ResponseCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId", "ProtoVersionId")
                        .IsUnique();

                    b.ToTable("feed_deliveries");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.FeedSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("FailCount")
                        .HasColumnType("integer")
                        .HasColumnName("fail_count");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset?>("LastDeliveryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_delivery_at");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("text")
                        .HasColumnName("message_template");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.PrimitiveCollection<string[]>("Platforms")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("platforms");

                    b.Property<string>("Secret")
                        .HasColumnType("text")
                        .HasColumnName("secret");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_url");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trigger");

                    b.HasKey("Id");

                    b.ToTable("feed_subscriptions");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.KnownVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_version");

                    b.Property<string>("Changelog")
                        .HasColumnType("text")
                        .HasColumnName("changelog");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("release_date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("Platform", "AppVersion", "Source")
                        .IsUnique();

                    b.ToTable("known_versions");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.ProtoProto", b =>
                {
                    b.Property<int>("ProtoVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("proto_version_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProtoVersionId"));

                    b.Property<string>("MessageIndex")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("message_index");

                    b.Property<string>("ProtoText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("proto_text");

                    b.HasKey("ProtoVersionId");

                    b.ToTable("proto_protos");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.ProtoVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApkRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apk_ref");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_version");

                    b.Property<string>("Build")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("build");

                    b.Property<int?>("CanonicalId")
                        .HasColumnType("integer")
                        .HasColumnName("canonical_id");

                    b.Property<string>("ClientVersion")
                        .HasColumnType("text")
                        .HasColumnName("client_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("DetectedBy")
                        .HasColumnType("text")
                        .HasColumnName("detected_by");

                    b.Property<string>("Package")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("package");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("ProtoSha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("proto_sha");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("Platform", "Build")
                        .IsUnique();

                    b.ToTable("proto_versions");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.StagedProto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppVersion")
                        .HasColumnType("text")
                        .HasColumnName("app_version");

                    b.Property<string>("Build")
                        .HasColumnType("text")
                        .HasColumnName("build");

                    b.Property<string>("ClientVersion")
                        .HasColumnType("text")
                        .HasColumnName("client_version");

                    b.Property<string>("Confidence")
                        .HasColumnType("text")
                        .HasColumnName("confidence");

                    b.Property<string>("MessageIndex")
                        .HasColumnType("text")
                        .HasColumnName("message_index");

                    b.Property<string>("OriginCommit")
                        .HasColumnType("text")
                        .HasColumnName("origin_commit");

                    b.Property<DateTimeOffset?>("OriginDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("origin_date");

                    b.Property<string>("OriginRepo")
                        .HasColumnType("text")
                        .HasColumnName("origin_repo");

                    b.Property<string>("Package")
                        .HasColumnType("text")
                        .HasColumnName("package");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("ProtoSha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("proto_sha");

                    b.Property<string>("ProtoText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("proto_text");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text")
                        .HasColumnName("review_note");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("SubmittedBy")
                        .HasColumnType("text")
                        .HasColumnName("submitted_by");

                    b.HasKey("Id");

                    b.HasIndex("ProtoSha");

                    b.HasIndex("Status");

                    b.ToTable("staged_protos");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.StoredEndpoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Eid")
                        .HasColumnType("text")
                        .HasColumnName("eid");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_json");

                    b.Property<string>("ResponseType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Path", "Eid")
                        .IsUnique();

                    b.ToTable("stored_endpoints");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.StoredMesh", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ByteSize")
                        .HasColumnType("integer")
                        .HasColumnName("byte_size");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<byte[]>("Glb")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("glb");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("Stem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stem");

                    b.HasKey("Id");

                    b.HasIndex("Platform", "Stem")
                        .IsUnique();

                    b.ToTable("stored_meshes");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.StoredRoute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<bool>("PathParam")
                        .HasColumnType("boolean")
                        .HasColumnName("path_param");

                    b.Property<bool>("PathParamOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("path_param_only");

                    b.Property<string>("RawResponse")
                        .HasColumnType("text")
                        .HasColumnName("raw_response");

                    b.Property<string>("RequestType")
                        .HasColumnType("text")
                        .HasColumnName("request_type");

                    b.Property<bool>("RequestWrapped")
                        .HasColumnType("boolean")
                        .HasColumnName("request_wrapped");

                    b.Property<string>("ResponseType")
                        .HasColumnType("text")
                        .HasColumnName("response_type");

                    b.Property<bool>("ResponseWrapped")
                        .HasColumnType("boolean")
                        .HasColumnName("response_wrapped");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("Source");

                    b.ToTable("stored_routes");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.SubjectTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("SubjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_key");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_kind");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint")
                        .HasColumnName("tag_id");

                    b.HasKey("Id");

                    b.HasIndex("SubjectKind", "SubjectKey", "TagId")
                        .IsUnique();

                    b.ToTable("subject_tags");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tags");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
