using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EggIncognito.Data.Migrations;

public partial class AddUserThemes : Migration {
    protected override void Up(MigrationBuilder migrationBuilder) {
        migrationBuilder.Sql("""
            create table user_themes (
                id bigint generated by default as identity primary key,
                owner_user_id uuid not null,
                name text not null,
                slug text not null,
                schema_version integer not null,
                model jsonb not null,
                is_active boolean not null default false,
                validated_at timestamptz null,
                validation jsonb null,
                created_at timestamptz not null default now(),
                updated_at timestamptz not null default now()
            );
            create index "IX_user_themes_owner_user_id" on user_themes (owner_user_id);
            create unique index "IX_user_themes_owner_user_id_slug" on user_themes (owner_user_id, slug);
            create unique index ix_user_themes_owner_active on user_themes (owner_user_id) where is_active;

            create table site_theme_policy (
                id integer primary key,
                custom_css_enabled boolean not null,
                default_theme_id bigint null,
                updated_at timestamptz not null,
                updated_by_user_id uuid null
            );
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder) {
        migrationBuilder.Sql("""
            drop table user_themes;
            drop table site_theme_policy;
            """);
    }
}
