using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EggIncognito.Data.Migrations;

/// <inheritdoc />
public partial class AddDeviceJobs : Migration {
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder) {
        migrationBuilder.Sql("""
            create table device_jobs (
                id bigint generated by default as identity primary key,
                device_id text not null,
                kind text not null,
                state text not null,
                trigger text not null,
                started_at timestamptz not null default now(),
                finished_at timestamptz null,
                outcome text null,
                message text null,
                reachable boolean null,
                app_version text null,
                build text null,
                client_version integer null,
                revision text null,
                detail jsonb null
            );
            create index "IX_device_jobs_device_id_id" on device_jobs (device_id, id);
            create index "IX_device_jobs_device_id_kind_id" on device_jobs (device_id, kind, id);
            create index "IX_device_jobs_state" on device_jobs (state);

            create table device_job_lines (
                id bigint generated by default as identity primary key,
                job_id bigint not null references device_jobs (id) on delete cascade,
                at timestamptz not null default now(),
                level text not null,
                text text not null,
                entry text null,
                bytes bigint null,
                sha256 text null
            );
            create index "IX_device_job_lines_job_id_id" on device_job_lines (job_id, id);
            """);

        migrationBuilder.Sql("""
            with runs as (
                select device_id, revision, min(ran_at) as started, max(ran_at) as finished,
                       count(*) filter (where outcome = 'failed') as failed,
                       count(*) as total
                from device_harvest_log
                group by device_id, revision
            ), history as (
                select device_id, 'probe' as kind, 'succeeded' as state,
                       coalesce(triggered_by, 'poll') as trigger,
                       probed_at as started_at, probed_at as finished_at, result as outcome, note as message,
                       reachable, installed_app_version as app_version, installed_build as build,
                       null::text as revision,
                       case when latest_available is null then null
                            else jsonb_build_object('latestAvailable', latest_available) end as detail
                from device_probes
                union all
                select device_id, 'store_check',
                       case when status = 'verified' then 'succeeded' else 'failed' end,
                       coalesce(triggered_by, 'auto'), attempted_at, attempted_at, status, note,
                       null::boolean, null::text, null::text, null::text,
                       jsonb_strip_nulls(jsonb_build_object('fromVersion', from_version, 'toVersion', to_version))
                from device_updates
                union all
                select device_id, 'harvest',
                       case when failed = 0 then 'succeeded' else 'failed' end,
                       'agent', started, finished,
                       case when failed = 0 then 'ok' else 'partial' end,
                       total || ' entries, ' || failed || ' failed',
                       null::boolean, null::text, null::text, revision,
                       null::jsonb
                from runs
            ), created as (
                insert into device_jobs
                    (device_id, kind, state, trigger, started_at, finished_at, outcome, message,
                     reachable, app_version, build, revision, detail)
                select device_id, kind, state, trigger, started_at, finished_at, outcome, message,
                       reachable, app_version, build, revision, detail
                from history
                order by started_at, device_id, kind, revision
                returning id, device_id, kind, revision
            )
            insert into device_job_lines (job_id, at, level, text, entry, bytes, sha256)
            select c.id, l.ran_at,
                   case when l.outcome = 'failed' then 'error' else 'info' end,
                   l.outcome || case when l.note is null then '' else ': ' || l.note end,
                   l.entry, l.byte_size, l.sha256
            from device_harvest_log l
            join created c on c.kind = 'harvest' and c.device_id = l.device_id and c.revision = l.revision
            order by l.ran_at, l.id;
            """);

        migrationBuilder.Sql("""
            drop table device_probes;
            drop table device_updates;
            drop table device_harvest_log;
            """);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder) {
        migrationBuilder.Sql("""
            create table device_probes (
                id integer generated by default as identity primary key,
                device_id text not null,
                probed_at timestamptz not null,
                reachable boolean not null,
                installed_app_version text null,
                installed_build text null,
                latest_available text null,
                result text not null,
                triggered_by text not null,
                note text null
            );
            create index ix_device_probes_device_id_probed_at on device_probes (device_id, probed_at);

            create table device_updates (
                id integer generated by default as identity primary key,
                device_id text not null,
                attempted_at timestamptz not null,
                from_version text null,
                to_version text null,
                status text not null,
                note text null,
                triggered_by text not null
            );
            create index ix_device_updates_device_id_attempted_at on device_updates (device_id, attempted_at);

            create table device_harvest_log (
                id bigint generated by default as identity primary key,
                device_id text not null,
                ran_at timestamptz not null default now(),
                revision text not null,
                entry text not null,
                kind text not null,
                outcome text not null,
                note text null,
                byte_size bigint not null,
                sha256 text null
            );
            create index ix_device_harvest_log_device_id_ran_at on device_harvest_log (device_id, ran_at);

            drop table device_job_lines;
            drop table device_jobs;
            """);
    }
}
