<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="AngleSharp" />
    <PackageReference Include="bunit" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\EggIncognito.Core\EggIncognito.Core.csproj" />
    <ProjectReference Include="..\..\EggIncognito.ExtractMcp\EggIncognito.ExtractMcp.csproj" Condition="Exists('..\..\EggIncognito.ExtractMcp\EggIncognito.ExtractMcp.csproj')" />
    <ProjectReference Include="..\..\EggIncognito.Capture\EggIncognito.Capture.csproj" />
    <ProjectReference Include="..\..\EggIncognito.Data\EggIncognito.Data.csproj" />
    <ProjectReference Include="..\EggIncognito.csproj" />
    <ProjectReference Include="..\..\EggIncognito.GameData\EggIncognito.GameData.csproj" />
    <ProjectReference Include="..\..\EggIncognito.Bot\EggIncognito.Bot.csproj" />
    <ProjectReference Include="..\..\EggIncognito.RouteGenerator\EggIncognito.RouteGenerator.csproj" />
    <ProjectReference Include="..\..\EggIncognito.RelayAgent\EggIncognito.RelayAgent.csproj" />
  </ItemGroup>

</Project>