using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace EggIncognito.Generator;

[Generator]
public sealed class EndpointSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var endpointsFile = context.AdditionalTextsProvider
            .Where(f => f.Path.EndsWith("endpoints.yaml", System.StringComparison.OrdinalIgnoreCase));

        context.RegisterSourceOutput(endpointsFile, (ctx, file) =>
        {
            var content = file.GetText(ctx.CancellationToken)?.ToString();
            if (content is null) return;

            foreach (var endpoint in EndpointParser.Parse(content))
            {
                var className = ToClassName(endpoint.Path);
                var source = GenerateController(className, endpoint);
                ctx.AddSource(className + ".g.cs", SourceText.From(source, Encoding.UTF8));
            }
        });
    }

    public static string ToClassName(string path) => EndpointParser.ToClassName(path);

    private static string GenerateController(string className, EndpointModel endpoint)
    {
        var handler = endpoint.RawResponse is not null
            ? "HandleRawAsync(\"" + endpoint.RawResponse + "\", sim)"
            : "HandleAsync<global::Ei." + endpoint.ResponseType + ">(\"" + endpoint.Path + "\", data, sim)";

        var paramMethod = endpoint.PathParam
            ? "\n" +
              "    [HttpPost(\"{param}\")]\n" +
              "    public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> HandleWithParam([Microsoft.AspNetCore.Mvc.FromRoute] string param, [Microsoft.AspNetCore.Mvc.FromForm(Name = \"data\")] string? data = null, [Microsoft.AspNetCore.Mvc.FromQuery(Name = \"sim\")] string? sim = null) =>\n" +
              "        HandleAsync<global::Ei." + endpoint.ResponseType + ">(\"" + endpoint.Path + "/\" + param, data, sim);\n"
            : "";

        return
            "// <auto-generated/>\n" +
            "#nullable enable\n" +
            "\n" +
            "using Microsoft.AspNetCore.Mvc;\n" +
            "using EggIncognito.Services;\n" +
            "\n" +
            "namespace EggIncognito.Controllers;\n" +
            "\n" +
            "[ApiController]\n" +
            "[Route(\"" + endpoint.Path + "\")]\n" +
            "public partial class " + className + " : MockApiControllerBase\n" +
            "{\n" +
            "    public " + className + "(IFixtureStore fixtures, IBehaviorService behaviors) : base(fixtures, behaviors) { }\n" +
            "\n" +
            "    [HttpPost]\n" +
            "    public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> Handle([Microsoft.AspNetCore.Mvc.FromForm(Name = \"data\")] string? data = null, [Microsoft.AspNetCore.Mvc.FromQuery(Name = \"sim\")] string? sim = null) =>\n" +
            "        " + handler + ";\n" +
            paramMethod +
            "}\n";
    }
}
