<Project>
  <PropertyGroup>
    <Authors>DavidArthurCole</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/DavidArthurCole/EggIncognito</RepositoryUrl>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MinVer" Version="7.0.0" PrivateAssets="All" />
    <PackageReference Include="EggIdentity.CodeStyle" Version="2.0.0" PrivateAssets="all" />
  </ItemGroup>
  <PropertyGroup>
    <MinVerTagPrefix>v</MinVerTagPrefix>
  </PropertyGroup>
  <Target Name="SetSourceRevisionId" BeforeTargets="GetAssemblyVersion" Condition="'$(SourceRevisionId)' == ''">
    <Exec Command="git rev-parse HEAD" ConsoleToMSBuild="true" ContinueOnError="true" StandardOutputImportance="low">
      <Output TaskParameter="ConsoleOutput" PropertyName="_GitSha" />
      <Output TaskParameter="ExitCode" PropertyName="_GitExit" />
    </Exec>
    <PropertyGroup Condition="'$(_GitExit)' == '0'">
      <SourceRevisionId>$(_GitSha)</SourceRevisionId>
    </PropertyGroup>
  </Target>
</Project>
