<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EggIdentity.Bot" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EggIncognito.Core\EggIncognito.Core.csproj" />
    <ProjectReference Include="..\EggIncognito.Capture\EggIncognito.Capture.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Migrations\*.up.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
