<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EggIdentity.Contract" Version="1.0.7" />
    <PackageReference Include="EggIdentity.Bot" Version="1.0.7" />
    <PackageReference Include="EggIdentity.Db" Version="1.0.7" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EggIncognito.Core\EggIncognito.Core.csproj" />
    <ProjectReference Include="..\EggIncognito.Capture\EggIncognito.Capture.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Migrations\*.up.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
