// Generated by EggIncognito.CodeGen - do not edit by hand
import io.ktor.server.application.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import java.io.File
import java.util.Base64

val FIXTURES_PATH: String = System.getenv("FIXTURES_PATH") ?: "Fixtures"

fun main() {
    val port = System.getenv("PORT")?.toIntOrNull() ?: {PORT}
    println("EggIncognito Kotlin mock server :$port  fixtures: $FIXTURES_PATH")
    embeddedServer(Netty, port = port) { module() }.start(wait = true)
}

fun Application.module() {
    routing {
        // GENERATED ROUTES - do not edit by hand
{ROUTES}
    }
}

private suspend fun serve(call: ApplicationCall, slug: String) {
    val data = call.receiveParameters()["data"] ?: ""
    val fixture = loadFixture(slug, extractEid(data))
    call.respondText(Base64.getEncoder().encodeToString(fixture), io.ktor.http.ContentType.Text.Html)
}

private fun loadFixture(slug: String, eid: String): ByteArray {
    if (eid.isNotEmpty()) {
        val f = File(FIXTURES_PATH, "eids/$eid/$slug.binpb")
        if (f.exists()) return f.readBytes()
    }
    val f = File(FIXTURES_PATH, "default/$slug.binpb")
    if (f.exists()) return f.readBytes()
    return ByteArray(0)
}

/** Read AuthenticatedMessage.user_id (field 6, wire type 2) from base64 data. */
private fun extractEid(data: String): String {
    if (data.isEmpty()) return ""
    return try { readProtoString(Base64.getDecoder().decode(data), 6) } catch (e: Exception) { "" }
}

private fun readProtoString(buf: ByteArray, fieldNumber: Int): String {
    var i = 0
    while (i < buf.size) {
        val (tag, n) = decodeVarint(buf, i)
        if (n == 0) break
        i += n
        val fn = tag shr 3; val wt = (tag and 7).toInt()
        when (wt) {
            0 -> { val (_, n2) = decodeVarint(buf, i); i += n2 }
            1 -> i += 8
            2 -> {
                val (length, n2) = decodeVarint(buf, i); i += n2
                if (fn == fieldNumber.toLong()) return buf.copyOfRange(i, i + length.toInt()).toString(Charsets.UTF_8)
                i += length.toInt()
            }
            5 -> i += 4
            else -> return ""
        }
    }
    return ""
}

private fun decodeVarint(buf: ByteArray, pos: Int): Pair<Long, Int> {
    var x = 0L; var s = 0
    for (i in pos until minOf(pos + 10, buf.size)) {
        val b = buf[i].toInt() and 0xFF
        x = x or ((b and 0x7F).toLong() shl s); s += 7
        if (b < 0x80) return Pair(x, i - pos + 1)
    }
    return Pair(0L, 0)
}
