#!/usr/bin/env python3
# Generated by EggIncognito.CodeGen - do not edit by hand
import base64
import os
from flask import Flask, request, Response

app = Flask(__name__)
FIXTURES_PATH = os.environ.get("FIXTURES_PATH", "Fixtures")
PORT = int(os.environ.get("PORT", "{PORT}"))


def _serve(slug: str) -> Response:
    data = request.form.get("data", "")
    fixture = _load_fixture(slug, _extract_eid(data))
    return Response(base64.b64encode(fixture).decode(), content_type="text/html")


def _load_fixture(slug: str, eid: str) -> bytes:
    if eid:
        path = os.path.join(FIXTURES_PATH, "eids", eid, slug + ".binpb")
        try:
            with open(path, "rb") as f:
                return f.read()
        except FileNotFoundError:
            pass
    path = os.path.join(FIXTURES_PATH, "default", slug + ".binpb")
    try:
        with open(path, "rb") as f:
            return f.read()
    except FileNotFoundError:
        return b""


def _extract_eid(data: str) -> str:
    # Read AuthenticatedMessage.user_id (field 6, wire type 2) from base64 data.
    try:
        return _read_proto_string(base64.b64decode(data), 6)
    except Exception:
        return ""


def _read_proto_string(data: bytes, field_number: int) -> str:
    i = 0
    while i < len(data):
        tag, n = _decode_varint(data, i)
        if n == 0:
            break
        i += n
        fn, wt = tag >> 3, tag & 7
        if wt == 0:
            _, n = _decode_varint(data, i)
            i += n
        elif wt == 1:
            i += 8
        elif wt == 2:
            length, n = _decode_varint(data, i)
            i += n
            if fn == field_number:
                return data[i:i + length].decode("utf-8", errors="replace")
            i += length
        elif wt == 5:
            i += 4
        else:
            break
    return ""


def _decode_varint(data: bytes, pos: int):
    x, s = 0, 0
    for i in range(pos, min(pos + 10, len(data))):
        b = data[i]
        x |= (b & 0x7F) << s
        s += 7
        if b < 0x80:
            return x, i - pos + 1
    return 0, 0


# GENERATED ROUTES - do not edit by hand
{ROUTES}

if __name__ == "__main__":
    print(f"EggIncognito Python mock server :{PORT}  fixtures: {FIXTURES_PATH}")
    app.run(host="0.0.0.0", port=PORT)
