# Generated by EggIncognito.CodeGen - do not edit by hand
require 'sinatra'
require 'base64'

FIXTURES_PATH = ENV.fetch('FIXTURES_PATH', 'Fixtures')
set :port, (ENV['PORT'] || '{PORT}').to_i
set :bind, '0.0.0.0'

def serve(slug)
  data = params[:data] || ''
  fixture = load_fixture(slug, extract_eid(data))
  content_type 'text/html'
  Base64.strict_encode64(fixture)
end

def load_fixture(slug, eid)
  if !eid.empty?
    path = File.join(FIXTURES_PATH, 'eids', eid, "#{slug}.binpb")
    return File.binread(path) if File.exist?(path)
  end
  path = File.join(FIXTURES_PATH, 'default', "#{slug}.binpb")
  File.exist?(path) ? File.binread(path) : ''
end

# Read AuthenticatedMessage.user_id (field 6, wire type 2) from base64 data.
def extract_eid(data)
  return '' if data.nil? || data.empty?
  read_proto_string(Base64.decode64(data), 6)
rescue
  ''
end

def read_proto_string(buf, field_number)
  i = 0
  while i < buf.bytesize
    tag, n = decode_varint(buf, i)
    break if n.zero?
    i += n
    fn = tag >> 3; wt = tag & 7
    case wt
    when 0 then _, n2 = decode_varint(buf, i); i += n2
    when 1 then i += 8
    when 2
      length, n2 = decode_varint(buf, i); i += n2
      return buf.byteslice(i, length).force_encoding('UTF-8') if fn == field_number
      i += length
    when 5 then i += 4
    else break
    end
  end
  ''
end

def decode_varint(buf, pos)
  x = 0; s = 0
  [pos, [pos + 10, buf.bytesize].min - 1].first.upto([pos + 10, buf.bytesize].min - 1) do |i|
    b = buf.getbyte(i)
    x |= (b & 0x7F) << s; s += 7
    return [x, i - pos + 1] if b < 0x80
  end
  [0, 0]
end

puts "EggIncognito Ruby mock server :#{settings.port}  fixtures: #{FIXTURES_PATH}"

# GENERATED ROUTES - do not edit by hand
{ROUTES}
