package com.egginc.mock;

// Generated by EggIncognito.CodeGen - do not edit by hand
import io.javalin.Javalin;
import io.javalin.http.Context;
import java.io.IOException;
import java.nio.file.*;
import java.util.Base64;

public class Server {
    static String FIXTURES_PATH =
        System.getenv().getOrDefault("FIXTURES_PATH", "Fixtures");

    public static void main(String[] args) {
        int port = Integer.parseInt(System.getenv().getOrDefault("PORT", "{PORT}"));
        var app = Javalin.create().start(port);
        System.out.printf("EggIncognito Java mock server :%d  fixtures: %s%n", port, FIXTURES_PATH);

        // GENERATED ROUTES - do not edit by hand
{ROUTES}
    }

    private static void serve(Context ctx, String slug) {
        byte[] fixture = loadFixture(slug, extractEid(ctx.formParam("data")));
        ctx.contentType("text/html").result(Base64.getEncoder().encodeToString(fixture));
    }

    static byte[] loadFixture(String slug, String eid) {
        if (eid != null && !eid.isEmpty()) {
            var p = Path.of(FIXTURES_PATH, "eids", eid, slug + ".binpb");
            if (Files.exists(p)) try { return Files.readAllBytes(p); } catch (IOException ignored) {}
        }
        var p = Path.of(FIXTURES_PATH, "default", slug + ".binpb");
        if (Files.exists(p)) try { return Files.readAllBytes(p); } catch (IOException ignored) {}
        return new byte[0];
    }

    /** Read AuthenticatedMessage.user_id (field 6, wire type 2) from base64 data. */
    static String extractEid(String data) {
        if (data == null || data.isEmpty()) return "";
        try {
            return readProtoString(Base64.getDecoder().decode(data), 6);
        } catch (Exception e) { return ""; }
    }

    private static String readProtoString(byte[] buf, int fieldNumber) {
        int i = 0;
        while (i < buf.length) {
            long[] r = decodeVarint(buf, i);
            if (r[1] == 0) break;
            i += (int) r[1];
            long tag = r[0], fn = tag >> 3, wt = tag & 7;
            if (wt == 0) { i += (int) decodeVarint(buf, i)[1]; }
            else if (wt == 1) { i += 8; }
            else if (wt == 2) {
                long[] lr = decodeVarint(buf, i); i += (int) lr[1];
                int len = (int) lr[0];
                if (fn == fieldNumber) return new String(buf, i, len, java.nio.charset.StandardCharsets.UTF_8);
                i += len;
            } else if (wt == 5) { i += 4; }
            else break;
        }
        return "";
    }

    private static long[] decodeVarint(byte[] buf, int pos) {
        long x = 0; int s = 0;
        for (int i = pos; i < Math.min(pos + 10, buf.length); i++) {
            int b = buf[i] & 0xFF;
            x |= (long)(b & 0x7F) << s; s += 7;
            if (b < 0x80) return new long[]{x, i - pos + 1};
        }
        return new long[]{0, 0};
    }
}
