using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace EggIncognito.RouteGenerator;

[Generator]
public sealed class RouteSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var routesFile = context.AdditionalTextsProvider
            .Where(f => f.Path.EndsWith("routes.yaml", System.StringComparison.OrdinalIgnoreCase));

        context.RegisterSourceOutput(routesFile, (ctx, file) =>
        {
            var content = file.GetText(ctx.CancellationToken)?.ToString();
            if (content is null) return;

            foreach (var route in RouteParser.Parse(content))
            {
                var className = ToClassName(route.Path);
                var source = GenerateController(className, route);
                ctx.AddSource(className + ".g.cs", SourceText.From(source, Encoding.UTF8));
            }
        });
    }

    public static string ToClassName(string path) => RouteParser.ToClassName(path);

    private static string GenerateController(string className, RouteModel route)
    {
        var handler = route.RawResponse is not null
            ? "HandleRawAsync(\"" + route.RawResponse + "\", sim)"
            : "HandleAsync<global::Ei." + route.MockResponseType + ">(\"" + route.Path + "\", data, sim)";

        var paramMethod = route.PathParam
            ? "\n" +
              "    [HttpPost(\"{param}\")]\n" +
              "    public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> HandleWithParam([Microsoft.AspNetCore.Mvc.FromRoute] string param, [Microsoft.AspNetCore.Mvc.FromForm(Name = \"data\")] string? data = null, [Microsoft.AspNetCore.Mvc.FromQuery(Name = \"sim\")] string? sim = null) =>\n" +
              "        HandleAsync<global::Ei." + route.MockResponseType + ">(\"" + route.Path + "/\" + param, data, sim);\n"
            : "";

        return
            "// <auto-generated/>\n" +
            "#nullable enable\n" +
            "\n" +
            "using Microsoft.AspNetCore.Mvc;\n" +
            "using EggIncognito.Services;\n" +
            "\n" +
            "namespace EggIncognito.Controllers;\n" +
            "\n" +
            "[ApiController]\n" +
            "[Route(\"" + route.Path + "\")]\n" +
            "public partial class " + className + " : MockApiControllerBase\n" +
            "{\n" +
            "    public " + className + "(IEndpointStore endpoints, IBehaviorService behaviors) : base(endpoints, behaviors) { }\n" +
            "\n" +
            "    [HttpPost]\n" +
            "    public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> Handle([Microsoft.AspNetCore.Mvc.FromForm(Name = \"data\")] string? data = null, [Microsoft.AspNetCore.Mvc.FromQuery(Name = \"sim\")] string? sim = null) =>\n" +
            "        " + handler + ";\n" +
            paramMethod +
            "}\n";
    }
}
