// AUTO-GENERATED by `dotnet run --project EggIncognito -- emit-types`.
// Source of truth: the C# records in EggIncognito.Capture. Do NOT edit by hand;
// re-run the emitter after changing a record. Field names are camelCased to match the
// JsonSerializerDefaults.Web casing used on the wire.

export interface DashboardFlow {
  id: number;
  timestamp?: string;
  path?: string;
  method?: string;
  status: number;
  requestJson?: string;
  responseJson?: string;
  responseB64?: string;
  requestDataB64?: string;
  requestType?: string;
  responseType?: string;
  known: boolean;
  outcome?: string;
  diffAdded: number;
  diffRemoved: number;
  requestJsonRaw?: string;
  responseJsonRaw?: string;
  url?: string;
  requestHeaders?: DashboardHeader[];
  responseHeaders?: DashboardHeader[];
  requestHeadersRaw?: DashboardHeader[];
  responseHeadersRaw?: DashboardHeader[];
}

export interface DashboardHeader {
  name?: string;
  value?: string;
  sensitive: boolean;
}

export interface CaptureStats {
  activeConnections: number;
  deviceCount: number;
  devices?: DeviceInfo[];
  capturedAuxbrain: number;
  passthrough: number;
  uniqueEndpoints: number;
  decryptOk: number;
  decryptErrors: number;
  lastError?: string;
  bytesCaptured: number;
  biggestEndpoint?: string;
  biggestEndpointBytes: number;
  certState?: string;
}

export interface DeviceInfo {
  ip?: string;
  hostname?: string;
  activeConnections: number;
  firstSeen?: string;
  lastSeen?: string;
  userAgent?: string;
}

