using System.Text;
using System.Text.RegularExpressions;
using EggIncognito.Services;

namespace EggIncognito.Cli;

// CLI port of scripts/Check-Endpoints.ps1. Classifies active routes by endpoint-file state and
// optionally rewrites the endpoint_status: block in routes.yaml (same regex-replace the script did;
// RoutesYamlEditor has no status-block writer, so the text edit is done here directly).
public static class CheckEndpointsCommand
{
    public sealed record Result(
        IReadOnlyList<string> Ok, IReadOnlyList<string> Empty, IReadOnlyList<string> Missing);

    public static Result Classify(string yamlPath, string defaultsDir)
    {
        var catalog = new RouteCatalog(yamlPath);
        var ok = new List<string>(); var empty = new List<string>(); var missing = new List<string>();
        foreach (var r in catalog.All())
        {
            if (r.RawResponse is not null) continue; // raw endpoints serve literals; no file needed
            var file = Path.Combine(defaultsDir, r.Path.Replace('/', Path.DirectorySeparatorChar) + ".json");
            if (!File.Exists(file)) { missing.Add(r.Path); continue; }
            var content = File.ReadAllText(file).Trim();
            if (content is "{}" or "{ }" or "") empty.Add(r.Path);
            else ok.Add(r.Path);
        }
        return new Result(ok, empty, missing);
    }

    public static int Run(string[] args)
    {
        var update = args.Contains("--update");
        var repoRoot = RepoPaths.FindRoot();
        var yamlPath = Path.Combine(repoRoot, "EggIncognito", "RouteMap", "routes.yaml");
        var defaultsDir = Path.Combine(repoRoot, "EggIncognito", "Endpoints", "default");
        var r = Classify(yamlPath, defaultsDir);

        var total = r.Ok.Count + r.Empty.Count + r.Missing.Count;
        Console.WriteLine($"\nEndpoint status ({total} active endpoints):");
        if (r.Ok.Count > 0) { Console.WriteLine($"\nOK ({r.Ok.Count}):"); foreach (var p in r.Ok) Console.WriteLine($"  {p}"); }
        if (r.Empty.Count > 0) { Console.WriteLine($"\nEmpty - endpoint is {{}} ({r.Empty.Count}):"); foreach (var p in r.Empty) Console.WriteLine($"  {p}"); }
        if (r.Missing.Count > 0) { Console.WriteLine($"\nMissing - no file ({r.Missing.Count}):"); foreach (var p in r.Missing) Console.WriteLine($"  {p}"); }

        if (!update) { Console.WriteLine("\nRun with --update to write results to routes.yaml."); return 0; }

        var sb = new StringBuilder();
        sb.Append("\nendpoint_status:\n");
        sb.Append("  # Auto-generated by `EggIncognito check-endpoints --update` - do not edit by hand\n");
        if (r.Empty.Count > 0)
        {
            sb.Append("  # Endpoints present but only default values - needs capture\n  empty:\n");
            foreach (var p in r.Empty) sb.Append($"    - {p}\n");
        }
        if (r.Missing.Count > 0)
        {
            sb.Append("  # No file exists - endpoint returns proto defaults\n  missing:\n");
            foreach (var p in r.Missing) sb.Append($"    - {p}\n");
        }

        var yaml = File.ReadAllText(yamlPath);
        yaml = Regex.Replace(yaml, @"(?s)\nendpoint_status:.*?(?=\n[a-z]|\z)", "");
        yaml = yaml.TrimEnd() + "\n" + sb.ToString().TrimStart('\n') + "\n";
        File.WriteAllText(yamlPath, yaml);
        Console.WriteLine("Updated endpoint_status in routes.yaml.");
        return 0;
    }
}
