using System.Collections.Generic;
using System.Text;

namespace EggIncognito.CodeGen.Generators;

public sealed class GoGenerator : IServerGenerator
{
    public string Language => "Go";

    private static string BuildRoutes(IReadOnlyList<EndpointEntry> endpoints) =>
        string.Join("\n", endpoints.Select(ep =>
            $"\tmux.HandleFunc(\"/{ep.Path}\", makeHandler(\"{ep.Slug}\"))"));

    public void Generate(IReadOnlyList<EndpointEntry> endpoints, string fixturesPath, string outputDir, int port)
    {
        var subs = new Dictionary<string, string>
        {
            ["PORT"] = port.ToString(),
            ["ROUTES"] = BuildRoutes(endpoints),
        };

        File.WriteAllText(Path.Combine(outputDir, "server.go"),
            TemplateLoader.Load("go", "server.go", subs), new UTF8Encoding(false));

        File.WriteAllText(Path.Combine(outputDir, "go.mod"),
            TemplateLoader.Load("go", "go.mod"), new UTF8Encoding(false));

        WriteReadme(outputDir, port,
            run: "go run .",
            prereqs: "Go 1.21+");
    }

    internal static void WriteReadme(string outputDir, int port, string run, string prereqs)
    {
        File.WriteAllText(Path.Combine(outputDir, "README.md"), $"""
            # EggIncognito Mock Server

            Generated by `EggIncognito.CodeGen`. Do not edit by hand.

            ## Prerequisites

            {prereqs}

            ## Run

            Fixtures are pre-baked and included. Start the server:

            ```sh
            {run}
            ```

            Server starts on port {port}.

            ## Configuration

            | Variable | Default | Description |
            |---|---|---|
            | `FIXTURES_PATH` | `Fixtures` | Path to fixtures directory |
            | `PORT` | `{port}` | HTTP listen port |

            ## Regenerate

            ```sh
            dotnet run --project EggIncognito.CodeGen -- generate {Path.GetFileName(outputDir)} --bake
            ```
            """, new UTF8Encoding(false));
    }
}
