#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Reports which active endpoints have missing or empty fixtures.

.DESCRIPTION
    Reads endpoints.yaml, checks Fixtures/default/ for each active endpoint,
    and updates the fixture_status section in endpoints.yaml with current state.

    Skips rawResponse endpoints (they serve literal strings, no fixture needed).

.PARAMETER Update
    Write results back into the fixture_status section of endpoints.yaml.
#>
[CmdletBinding()]
param([switch] $Update)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot    = Split-Path -Parent $PSScriptRoot
$yamlPath    = Join-Path $repoRoot 'EggIncognito' 'EndpointMap' 'endpoints.yaml'
$fixturesDir = Join-Path $repoRoot 'EggIncognito' 'Fixtures' 'default'

$yaml = Get-Content $yamlPath -Raw

# Parse active endpoints (exclude rawResponse ones)
$missing = [System.Collections.Generic.List[string]]::new()
$empty   = [System.Collections.Generic.List[string]]::new()
$ok      = [System.Collections.Generic.List[string]]::new()

$path = $null
$isRaw = $false

foreach ($line in $yaml -split "`n") {
    $t = $line.Trim()
    if ($t -match '^- path:\s+(\S+)') {
        $path  = $Matches[1]
        $isRaw = $false
    } elseif ($t -match '^rawResponse:') {
        $isRaw = $true
    } elseif ($t -match '^responseType:' -and $path -and -not $isRaw) {
        $file = Join-Path $fixturesDir ($path + '.json')
        if (-not (Test-Path $file)) {
            $missing.Add($path)
        } else {
            $content = (Get-Content $file -Raw).Trim()
            if ($content -in '{}', '{ }', '') {
                $empty.Add($path)
            } else {
                $ok.Add($path)
            }
        }
        $path = $null
    }
}

# Report
$total = $missing.Count + $empty.Count + $ok.Count
Write-Host ""
Write-Host "Fixture status ($total active endpoints):" -ForegroundColor Cyan

if ($ok.Count -gt 0) {
    Write-Host ""
    Write-Host "OK ($($ok.Count)):" -ForegroundColor Green
    $ok | ForEach-Object { Write-Host "  $_ " -ForegroundColor Green }
}

if ($empty.Count -gt 0) {
    Write-Host ""
    Write-Host "Empty - fixture is {} ($($empty.Count)):" -ForegroundColor Yellow
    $empty | ForEach-Object { Write-Host "  $_" -ForegroundColor Yellow }
}

if ($missing.Count -gt 0) {
    Write-Host ""
    Write-Host "Missing - no fixture file ($($missing.Count)):" -ForegroundColor Red
    $missing | ForEach-Object { Write-Host "  $_" -ForegroundColor Red }
}

Write-Host ""

if (-not $Update) {
    Write-Host "Run with -Update to write results to endpoints.yaml." -ForegroundColor Cyan
    exit 0
}

# Build replacement block
$lines = @('', 'fixture_status:')
$lines += '  # Auto-generated by Check-Fixtures.ps1 - do not edit by hand'

if ($empty.Count -gt 0) {
    $lines += '  # Fixtures present but contain only default values - needs capture'
    $lines += '  empty:'
    $empty  | ForEach-Object { $lines += "    - $_" }
}

if ($missing.Count -gt 0) {
    $lines += '  # No fixture file exists - endpoint will return proto defaults'
    $lines += '  missing:'
    $missing | ForEach-Object { $lines += "    - $_" }
}

$block = $lines -join "`n"

# Remove existing fixture_status block if present
$yaml = [System.Text.RegularExpressions.Regex]::Replace(
    $yaml,
    '(?m)^\nfixture_status:.*?(?=\n[a-z]|\z)',
    '',
    [System.Text.RegularExpressions.RegexOptions]::Singleline
)

$yaml = $yaml.TrimEnd() + "`n" + $block + "`n"
Set-Content -Path $yamlPath -Value $yaml -NoNewline
Write-Host "Updated fixture_status in endpoints.yaml." -ForegroundColor Green
