using System.Collections;
using System.Reflection;
using System.Text;
using EggIncognito.Tooling.Dashboard;

namespace EggIncognito.Tooling;

// Emits a TypeScript declaration file (wwwroot/capture/types.d.ts) describing the JSON shapes the
// dashboard backend sends over SSE / the REST API. Generated FROM the actual C# records by
// reflection, so the JS side has one source of truth and the editor flags a field-name typo or a
// renamed property. Property names are lower-camelCased to match JsonSerializerDefaults.Web.
//
// Run: `dotnet run --project EggIncognito.Tooling -- emit-types`
// The JS modules reference these via JSDoc:  /** @typedef {import('./types.d.ts').DashboardFlow} ... */
public static class TypeEmitter
{
    // The record types the dashboard consumes. Add new wire types here.
    private static readonly Type[] Roots =
    [
        typeof(DashboardFlow),
        typeof(DashboardHeader),
        typeof(CaptureStats),
    ];

    public static int Run(string repoRoot)
    {
        var emitted = new Dictionary<string, string>(StringComparer.Ordinal);
        var queue = new Queue<Type>(Roots);
        var seen = new HashSet<Type>();

        while (queue.Count > 0)
        {
            var t = queue.Dequeue();
            if (!seen.Add(t)) continue;
            emitted[t.Name] = EmitType(t, queue);
        }

        var sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED by `dotnet run --project EggIncognito.Tooling -- emit-types`.");
        sb.AppendLine("// Source of truth: the C# records in EggIncognito.Tooling/Dashboard. Do NOT edit by hand;");
        sb.AppendLine("// re-run the emitter after changing a record. Field names are camelCased to match the");
        sb.AppendLine("// JsonSerializerDefaults.Web casing used on the wire.");
        sb.AppendLine();
        // Stable order: roots first in declared order, then the rest alphabetically.
        foreach (var name in Roots.Select(r => r.Name).Concat(emitted.Keys.Except(Roots.Select(r => r.Name)).OrderBy(x => x)))
            if (emitted.TryGetValue(name, out var body))
                sb.AppendLine(body);

        var outPath = Path.Combine(repoRoot, "EggIncognito.Tooling", "wwwroot", "capture", "types.d.ts");
        File.WriteAllText(outPath, sb.ToString(), new UTF8Encoding(false));
        Console.WriteLine($"Wrote {outPath} ({emitted.Count} types)");
        return 0;
    }

    private static string EmitType(Type t, Queue<Type> queue)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"export interface {t.Name} {{");
        // Records expose their data as public instance properties (one per positional/init member).
        foreach (var p in t.GetProperties(BindingFlags.Public | BindingFlags.Instance))
        {
            if (p.GetIndexParameters().Length > 0) continue; // skip indexers (e.g. EqualityContract)
            if (p.Name == "EqualityContract") continue;
            var (ts, optional) = TsType(p.PropertyType, queue);
            sb.AppendLine($"  {CamelCase(p.Name)}{(optional ? "?" : "")}: {ts};");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    // Map a CLR type to a TS type. Enqueues nested record types for emission. Returns (tsType,
    // isOptional) - reference/nullable types are optional since the JSON may omit/null them.
    private static (string ts, bool optional) TsType(Type t, Queue<Type> queue)
    {
        var underlying = Nullable.GetUnderlyingType(t);
        if (underlying is not null) return (TsType(underlying, queue).ts, true);

        if (t == typeof(string)) return ("string", true);
        if (t == typeof(bool)) return ("boolean", false);
        if (t == typeof(int) || t == typeof(long) || t == typeof(uint) || t == typeof(ulong)
            || t == typeof(double) || t == typeof(float) || t == typeof(decimal) || t == typeof(short))
            return ("number", false);

        // List<T> / IReadOnlyList<T> / arrays -> T[]
        if (t.IsArray)
        {
            var (el, _) = TsType(t.GetElementType()!, queue);
            return ($"{el}[]", true);
        }
        if (t.IsGenericType && typeof(IEnumerable).IsAssignableFrom(t))
        {
            var arg = t.GetGenericArguments()[0];
            var (el, _) = TsType(arg, queue);
            return ($"{el}[]", true);
        }

        // A nested record/class we also emit.
        if (t.Namespace?.StartsWith("EggIncognito") == true)
        {
            queue.Enqueue(t);
            return (t.Name, true);
        }

        return ("unknown", true);
    }

    private static string CamelCase(string s) =>
        string.IsNullOrEmpty(s) || char.IsLower(s[0]) ? s : char.ToLowerInvariant(s[0]) + s[1..];
}
