// Generated by EggIncognito.CodeGen - do not edit by hand
'use strict';
const express = require('express');
const fs      = require('fs');
const path    = require('path');

let FIXTURES_PATH = process.env.FIXTURES_PATH ?? 'Fixtures';
const PORT          = parseInt(process.env.PORT ?? '{PORT}', 10);

const app = express();
app.use(express.urlencoded({ extended: false }));

function makeHandler(slug) {
  return (req, res) => {
    const fixture = loadFixture(slug, extractEid(req.body?.data ?? ''));
    res.set('Content-Type', 'text/html').send(fixture.toString('base64'));
  };
}

function loadFixture(slug, eid) {
  if (eid) {
    const eidPath = path.join(FIXTURES_PATH, 'eids', eid, `${slug}.binpb`);
    if (fs.existsSync(eidPath)) return fs.readFileSync(eidPath);
  }
  const defPath = path.join(FIXTURES_PATH, 'default', `${slug}.binpb`);
  if (fs.existsSync(defPath)) return fs.readFileSync(defPath);
  return Buffer.alloc(0);
}

/** Read AuthenticatedMessage.user_id (field 6, wire type 2) from base64 data. */
function extractEid(data) {
  try {
    return readProtoString(Buffer.from(data, 'base64'), 6);
  } catch {
    return '';
  }
}

function readProtoString(buf, fieldNumber) {
  let i = 0;
  while (i < buf.length) {
    const [tag, n] = decodeVarint(buf, i);
    if (n === 0) break;
    i += n;
    const fn = tag >> 3n, wt = Number(tag & 7n);
    if (wt === 0) {
      const [, n2] = decodeVarint(buf, i); i += n2;
    } else if (wt === 1) {
      i += 8;
    } else if (wt === 2) {
      const [length, n2] = decodeVarint(buf, i); i += n2;
      if (fn === BigInt(fieldNumber)) return buf.slice(i, i + Number(length)).toString('utf8');
      i += Number(length);
    } else if (wt === 5) {
      i += 4;
    } else break;
  }
  return '';
}

function decodeVarint(buf, pos) {
  let x = 0n, s = 0n;
  for (let i = pos; i < Math.min(pos + 10, buf.length); i++) {
    const b = buf[i];
    x |= BigInt(b & 0x7f) << s;
    s += 7n;
    if (b < 0x80) return [x, i - pos + 1];
  }
  return [0n, 0];
}

// GENERATED ROUTES - do not edit by hand
{ROUTES}

if (require.main === module) {
  app.listen(PORT, () => {
    console.log(`EggIncognito JS mock server :${PORT}  fixtures: ${FIXTURES_PATH}`);
  });
}

module.exports = { extractEid, loadFixture };
