using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

namespace EggIncognito.Core.Services;

public static partial class EndpointStatus {
    public static Result Classify(string yamlPath, string defaultsDir) {
        var catalog = new RouteCatalog(yamlPath);
        var ok = new List<string>();
        var empty = new List<string>();
        var missing = new List<string>();
        foreach (var r in catalog.All()) {
            if (r.RawResponse is not null) continue;
            string file = Path.Combine(defaultsDir, r.Path.Replace('/', Path.DirectorySeparatorChar) + ".json");
            if (!File.Exists(file)) {
                missing.Add(r.Path);
                continue;
            }

            string compact = WhitespaceRegex().Replace(File.ReadAllText(file), "");
            if (compact is "{}" or "") empty.Add(r.Path);
            else ok.Add(r.Path);
        }

        return new Result(ok, empty, missing);
    }


    public static string WriteStatusBlock(string yamlPath, Result r) {
        var sb = new StringBuilder();
        sb.Append("\nendpoint_status:\n");
        sb.Append("  # Auto-generated by the endpoint-status tool - do not edit by hand\n");
        if (r.Empty.Count > 0) {
            sb.Append("  # Endpoints present but only default values - needs capture\n  empty:\n");
            foreach (string p in r.Empty) sb.Append(CultureInfo.InvariantCulture, $"    - {p}\n");
        }

        if (r.Missing.Count > 0) {
            sb.Append("  # No file exists - endpoint returns proto defaults\n  missing:\n");
            foreach (string p in r.Missing) sb.Append(CultureInfo.InvariantCulture, $"    - {p}\n");
        }

        string yaml = File.ReadAllText(yamlPath);


        yaml = EndpointStatusBlockRegex().Replace(yaml, "");
        yaml = yaml.TrimEnd() + "\n" + sb.ToString().TrimStart('\n') + "\n";
        File.WriteAllText(yamlPath, yaml);
        return yaml;
    }

    [GeneratedRegex(@"\s")]
    private static partial Regex WhitespaceRegex();

    [GeneratedRegex(@"(?s)\nendpoint_status:.*?(?=\n\w[\w_]*:|\z)")]
    private static partial Regex EndpointStatusBlockRegex();

    public sealed record Result(
        IReadOnlyList<string> Ok,
        IReadOnlyList<string> Empty,
        IReadOnlyList<string> Missing);
}
